FROM debian:bookworm-slim@sha256:936abff852736f951dab72d91a1b6337cf04217b2a77a5eaadc7c0f2f1ec1758 AS builder

ARG RR_TAG="v2.3"

RUN apt-get update -y \
	&& apt-get upgrade -y \
	&& apt-get install -y \
	build-essential \
	git \
	cmake \
	libcurl4-openssl-dev \
	libgme-dev \
	libogg-dev \
	libopenmpt-dev \
	libpng-dev \
	libsdl2-dev \
	libsdl2-mixer-dev \
	libvorbis-dev \
	libvpx-dev \
	libyuv-dev \
	nasm \
	ninja-build \
	p7zip-full \
	pkg-config \
	zlib1g-dev \
	&& apt-get clean

RUN git clone https://github.com/KartKrewDev/RingRacers.git /home/ringracers/rr_git
WORKDIR /home/ringracers/rr_git
RUN git checkout ${RR_TAG}
RUN cmake --preset ninja-release
RUN cmake --build --preset ninja-release

# --------------
FROM debian:bookworm-slim@sha256:936abff852736f951dab72d91a1b6337cf04217b2a77a5eaadc7c0f2f1ec1758 AS assets

ARG RR_TAG="v2.3"
ARG ASSETS_URL="https://github.com/KartKrewDev/RingRacers/releases/download/${RR_TAG}/Dr.Robotnik.s-Ring-Racers-${RR_TAG}-Assets.zip"

RUN apt-get update -y \
	&& apt-get upgrade -y \
	&& apt-get install -y wget unzip \
	&& apt-get clean

RUN mkdir /RingRacers
WORKDIR /RingRacers
RUN wget ${ASSETS_URL}
RUN unzip "Dr.Robotnik.s-Ring-Racers-${RR_TAG}-Assets.zip"

# --------------

FROM debian:bookworm-slim@sha256:936abff852736f951dab72d91a1b6337cf04217b2a77a5eaadc7c0f2f1ec1758 AS main

ARG RR_PORT="5029"
ARG RR_TAG="v2.3"
ARG ADVERTISE="Yes"

ENV RR_PORT=${RR_PORT}
ENV ADVERTISE=${ADVERTISE}

RUN apt-get update \
	&& apt-get install -y \
	libcurl4 \
	libgme0 \
	libogg0 \
	libpng16-16 \
	libsdl2-2.0-0 \
	libsdl2-mixer-2.0-0 \
	libvorbis0a \
	libvpx7 \
	libyuv0 \
	procps \
	tmux \
	&& apt-get clean

WORKDIR /home/ringracers/
COPY --from=assets  /RingRacers/data/* data/
COPY --from=assets  /RingRacers/models/* models/
COPY --from=assets  /RingRacers/bios.pk3 bios.pk3
COPY --from=assets  /RingRacers/models.dat models.dat
COPY --from=builder /home/ringracers/rr_git/build/ninja-release/bin/ringracers_${RR_TAG} ringracers

VOLUME /home/ringracers/.ringracers
EXPOSE ${RR_PORT}/udp

ENV LOG_FILE="/home/ringracers/.ringracers/latest-log.txt"
ENV ADDON_DIR="/home/ringracers/.ringracers/addons"

COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ./entrypoint.sh
